// Generated by Selenium IDE
import es.uca.iw.Application;
import es.uca.iw.Tarifa.ServiciosTarifa;
import es.uca.iw.Tarifa.Tarifa;
import es.uca.iw.cliente.Cliente;
import es.uca.iw.cliente.ServiciosCliente;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.springframework.test.util.AssertionErrors.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.event.annotation.AfterTestExecution;
import org.springframework.test.context.event.annotation.BeforeTestExecution;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@SpringBootTest(classes = Application.class)
public class TarifaTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    private final ServiciosTarifa servicios;

    @Autowired
    public TarifaTest(ServiciosTarifa servicios) {
        this.servicios = servicios;
    }

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }
    @AfterEach
    public void tearDown() {
        if(driver != null)
            driver.quit();
    }

    @Test
    public void tarifa() {
        Optional<Tarifa> tarifa = servicios.cargarTarifaPorNombre("Tarifa Roaming Básica");
        boolean roaming,fijo, fibra;
        roaming = fijo = fibra = false;
        if(tarifa.isPresent()){
            roaming = tarifa.get().getpermiteRoaming();
            fijo = tarifa.get().getfijo();
            fibra = tarifa.get().getfibra();
        }



        driver.get("http://localhost:8080/tarifa-view");
        driver.manage().window().setSize(new Dimension(1066, 816));
        driver.findElement(By.cssSelector("vaadin-combo-box")).click();
        driver.findElement(By.id("vaadin-combo-box-item-0")).click();
        driver.findElement(By.id("input-vaadin-checkbox-25")).click();
        driver.findElement(By.id("input-vaadin-checkbox-24")).click();
        driver.findElement(By.id("input-vaadin-checkbox-22")).click();
        driver.findElement(By.cssSelector("vaadin-button")).click();


        try {
            // Pausa el hilo actual durante 1000 milisegundos (1 segundo)
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            // Maneja la excepción si es interrumpida durante la pausa
            e.printStackTrace();
        }

        tarifa = servicios.cargarTarifaPorNombre("Tarifa Roaming Básica");
        if(tarifa.isPresent()){
            assert roaming != tarifa.get().getpermiteRoaming() : "El valor de roaming no coincide";
            assert fijo != tarifa.get().getfijo() : "El valor de fijo no coincide";
            assert fibra != tarifa.get().getfibra() : "El valor de fibra no coincide";
        }

        driver.get("http://localhost:8080/tarifa-view");
        driver.manage().window().setSize(new Dimension(1066, 816));
        driver.findElement(By.cssSelector("vaadin-combo-box")).click();
        driver.findElement(By.id("vaadin-combo-box-item-0")).click();
        driver.findElement(By.id("input-vaadin-checkbox-25")).click();
        driver.findElement(By.id("input-vaadin-checkbox-24")).click();
        driver.findElement(By.id("input-vaadin-checkbox-22")).click();
        driver.findElement(By.cssSelector("vaadin-button")).click();
    }
}
