// Generated by Selenium IDE
import es.uca.iw.Application;
import es.uca.iw.tarifa.TarifaService;
import es.uca.iw.tarifa.Tarifa;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.time.Duration;
import java.util.*;

@SpringBootTest(classes = Application.class)
public class TarifaTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    private final TarifaService servicios;

    @Autowired
    public TarifaTest(TarifaService servicios) {
        this.servicios = servicios;
    }

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }
    @AfterEach
    public void tearDown() {
        if(driver != null)
            driver.quit();
    }

    @Test
    public void tarifa() {
        Optional<Tarifa> tarifa = servicios.cargarTarifaPorNombre("Tarifa Roaming Básica");
        boolean roaming,fijo, fibra;
        roaming = fijo = fibra = false;
        if(tarifa.isPresent()){
            roaming = tarifa.get().isPermiteRoaming();
            fijo = tarifa.get().isFijo();
            fibra = tarifa.get().isFibra();
        }



        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(1066, 816));
        driver.findElement(By.id("input-vaadin-text-field-7")).click();
        driver.findElement(By.id("input-vaadin-text-field-7")).sendKeys("marketing@gmail.com");
        driver.findElement(By.id("input-vaadin-text-field-7")).sendKeys(Keys.ENTER);
        driver.findElement(By.id("input-vaadin-password-field-8")).sendKeys("1234");
        driver.findElement(By.id("input-vaadin-password-field-8")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("vaadin-side-nav-item:nth-child(2)")).click();
        driver.findElement(By.cssSelector("vaadin-combo-box")).click();
        driver.findElement(By.id("vaadin-combo-box-item-0")).click();
        driver.findElement(By.id("input-vaadin-checkbox-32")).click();
        driver.findElement(By.id("input-vaadin-checkbox-31")).click();
        driver.findElement(By.id("input-vaadin-checkbox-29")).click();
        driver.findElement(By.cssSelector("vaadin-button")).click();


        try {
            // Pausa el hilo actual durante 1000 milisegundos (1 segundo)
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            // Maneja la excepción si es interrumpida durante la pausa
            e.printStackTrace();
        }

        tarifa = servicios.cargarTarifaPorNombre("Tarifa Roaming Básica");
        if(tarifa.isPresent()){
            assert roaming != tarifa.get().isPermiteRoaming() : "El valor de roaming no coincide";
            assert fijo != tarifa.get().isFijo() : "El valor de fijo no coincide";
            assert fibra != tarifa.get().isFibra() : "El valor de fibra no coincide";
        }

        driver.get("http://localhost:8080/profile");
        driver.manage().window().setSize(new Dimension(1066, 816));
        driver.findElement(By.cssSelector("vaadin-side-nav-item:nth-child(2)")).click();
        driver.findElement(By.cssSelector("vaadin-combo-box")).click();
        driver.findElement(By.id("vaadin-combo-box-item-0")).click();
        driver.findElement(By.id("input-vaadin-checkbox-32")).click();
        driver.findElement(By.id("input-vaadin-checkbox-31")).click();
        driver.findElement(By.id("input-vaadin-checkbox-29")).click();
        driver.findElement(By.cssSelector("vaadin-button")).click();
    }
}
